// Header
#include "StorageDescription.h"
#include "Global.h"

// Variables
RecordDescription StorageDescription[] =
{
		{"REG 1 Shunt Resistance (mOhm)",	DT_Int16U, 1},
		{"EP 1 Array of current values",	DT_Int16U, 300},
};
Int32U TablePointers[sizeof(StorageDescription) / sizeof(StorageDescription[0])] = {0};
const Int16U StorageSize = sizeof(StorageDescription) / sizeof(StorageDescription[0]);

RecordDescription CounterStorageDescription[] =
{
		{"0. Collector (C_POT) to PE",								DT_Int32U, 1},
		{"1. Gate (G) to PE",										DT_Int32U, 1},
		{"2. Gate-Emitter (GE) to PE",								DT_Int32U, 1},
		{"3. Emitter (E_POT) to PE",								DT_Int32U, 1},
		{"4. Collector: Commutation of C_POT (Open/Close)",			DT_Int32U, 1},
		{"5. Gate: Commutation of G (Open/Close)",					DT_Int32U, 1},
		{"6. Gate-Emitter: Commutation of GE (Open/Close)",			DT_Int32U, 1},
		{"7. Emitter: Commutation of E_POT (Open/Close)",			DT_Int32U, 1},
		{"8. Gate (G) to Collector (C_POT)",						DT_Int32U, 1},
		{"9. Gate (G) to Gate-Emitter (GE)",						DT_Int32U, 1},
		{"10. Gate-Emitter (GE) to GT_G",							DT_Int32U, 1},
		{"11. Gate-Emitter (GE) to GT_GE",							DT_Int32U, 1},
		{"12. Gate-Emitter (GE) to LSL_GE",							DT_Int32U, 1},
		{"13. Gate (G) to GT_G",									DT_Int32U, 1},
		{"14. Gate (G) to GT_GE",									DT_Int32U, 1},
		{"15. Gate (G) to GT_G_POT",								DT_Int32U, 1},
		{"16. Emitter (E_POT) to GT_GE_POT",						DT_Int32U, 1},
		{"17. Emitter (E_POT) to LSL_POT+",							DT_Int32U, 1},
		{"18. Emitter (E_POT) to LSL_POT-",							DT_Int32U, 1},
		{"19. Gate (G) to LSL_G",									DT_Int32U, 1},
		{"20. Collector (C_POT) to LSL_POT+",						DT_Int32U, 1},
		{"21. Collector (C_POT) to LSL_POT-",						DT_Int32U, 1},
		{"22. None",												DT_Int32U, 1},
		{"23. None",												DT_Int32U, 1},
		{"24. Collector (C_POT) to PE",								DT_Int32U, 1},
		{"25. Gate (G) to PE",										DT_Int32U, 1},
		{"26. Gate-Emitter (GE) to PE",								DT_Int32U, 1},
		{"27. Emitter (E_POT) to PE",								DT_Int32U, 1},
		{"28. Collector: Commutation of C_POT (Open/Close)",		DT_Int32U, 1},
		{"29. Gate: Commutation of G (Open/Close)",					DT_Int32U, 1},
		{"30. Gate-Emitter: Commutation of GE (Open/Close)",		DT_Int32U, 1},
		{"31. Emitter: Commutation of E_POT (Open/Close)",			DT_Int32U, 1},
		{"32. Gate (G) to Collector (C_POT)",						DT_Int32U, 1},
		{"33. Gate (G) to Gate-Emitter (GE)",						DT_Int32U, 1},
		{"34. Gate-Emitter (GE) to GT_G",							DT_Int32U, 1},
		{"35. Gate-Emitter (GE) to GT_GE",							DT_Int32U, 1},
		{"36. Gate-Emitter (GE) to LSL_GE",							DT_Int32U, 1},
		{"37. Gate (G) to GT_G",									DT_Int32U, 1},
		{"38. Gate (G) to GT_GE",									DT_Int32U, 1},
		{"39. Gate (G) to GT_G_POT",								DT_Int32U, 1},
		{"40. Emitter (E_POT) to GT_GE_POT",						DT_Int32U, 1},
		{"41. Emitter (E_POT) to LSL_POT+",							DT_Int32U, 1},
		{"42. Emitter (E_POT) to LSL_POT-",							DT_Int32U, 1},
		{"43. Gate (G) to LSL_G",									DT_Int32U, 1},
		{"44. Collector (C_POT) to LSL_POT+",						DT_Int32U, 1},
		{"45. Collector (C_POT) to LSL_POT-",						DT_Int32U, 1},
		{"46. None",												DT_Int32U, 1},
		{"47. None",												DT_Int32U, 1},
		{"48. Thermistor_1 (T1) to PE",								DT_Int32U, 1},
		{"49. Thermistor_2 (T2) to PE",								DT_Int32U, 1},
		{"50. Thermistor_1: Commutation of T1 (Open/Close)",		DT_Int32U, 1},
		{"51. Thermistor_2: Commutation of T2 (Open/Close)",		DT_Int32U, 1},
		{"52. T2 to GT_G",											DT_Int32U, 1},
		{"53. T2 to GT_G_POT",										DT_Int32U, 1},
		{"54. T1 to GT_GE",											DT_Int32U, 1},
		{"55. T1 to GT_GE_POT",										DT_Int32U, 1},
		{"56. GT_G to TEST-IN",										DT_Int32U, 1},
		{"57. GT_GE to TEST-OUT",									DT_Int32U, 1},
		{"58. GT_G: Commutation of GT_G (Open/Close)",				DT_Int32U, 1},
		{"59. GT_GE: Commutation of GT_GE (Open/Close)",			DT_Int32U, 1},
		{"60. GT_G to GT_GE",										DT_Int32U, 1},
		{"61. GT_G_POT to TEST-IN",									DT_Int32U, 1},
		{"62. GT_GE_POT to TEST-OUT",								DT_Int32U, 1},
		{"63. GT_G_POT: Commutation of GT_G_POT (Open/Close)",		DT_Int32U, 1},
		{"64. GT_GE_POT: Commutation of GT_GE_POT (Open/Close)",	DT_Int32U, 1},
		{"65. GT_G_POT to GT_GE_POT",								DT_Int32U, 1},
		{"66. LSL_G to TEST-IN",									DT_Int32U, 1},
		{"67. LSL_GE to TEST-OUT",									DT_Int32U, 1},
		{"68. LSL_G: Commutation of LSL_G (Open/Close)",			DT_Int32U, 1},
		{"69. LSL_GE: Commutation of LSL_GE (Open/Close)",			DT_Int32U, 1},
		{"70. LSL_G to LSL_GE",										DT_Int32U, 1},
		{"71. LSL_POT+ to TEST-IN",									DT_Int32U, 1},
		{"72. LSL_POT- to TEST-OUT",								DT_Int32U, 1},
		{"73. LSL_POT+: Commutation of LSL_POT+ (Open/Close)",		DT_Int32U, 1},
		{"74. LSL_POT-: Commutation of LSL_POT- (Open/Close)",		DT_Int32U, 1},
		{"75. LSL_POT+ to LSL_POT-",								DT_Int32U, 1},
		{"76. None",												DT_Int32U, 1},
		{"77. None",												DT_Int32U, 1},
		{"78. None",												DT_Int32U, 1},
		{"79. None",												DT_Int32U, 1}
};
CounterData CounterTablePointers[sizeof(CounterStorageDescription) / sizeof(CounterStorageDescription[0])] = {0};
const Int16U CounterStorageSize = sizeof(CounterStorageDescription) / sizeof(CounterStorageDescription[0]);

