// Header
//
#include "SelfTestRelaysArrays.h"

// Arrays
//
const Int16U SelfTestInputBoard[ST_INPUT_BOARD_STAGES][ST_INPUT_BOARD_RELAYS] =
{
		{ST_TI_GT_G, IL_GT_G_COMM, IL_GT_GE_COMM, IL_GT_G_GE, ST_TO_GT_GE},
		{IL_GT_G_POT_COMM, IL_GT_GE_POT_COMM, ST_TI_GT_G_POT, ST_TO_GT_GE_POT, IL_GT_G_GE_POT},
		{IL_LSL_G_COMM, IL_LSL_GE_COMM, ST_TI_LSL_G, ST_TO_LSL_GE, IL_LSL_G_GE},
		{IL_LSL_POTP_COMM, IL_LSL_POTN_COMM, ST_TI_LSL_POTP, ST_TO_LSL_POTN, IL_LSL_POTS}
};

const Int16U SelfTestThermBoard[ST_THERM_BOARD_STAGES][ST_THERM_BOARD_RELAYS] =
{
		{OL_T_COMM_1, OL_T_COMM_2, T_PE_1, T_PE_2, MC_T_GT_G_2, MC_T_GT_GE_1, ST_TI_GT_G, ST_TO_GT_GE},
		{OL_T_COMM_1, OL_T_COMM_2, T_PE_1, T_PE_2, MC_T_GT_G_POT_2, MC_T_GT_GE_POT_1, ST_TI_GT_G_POT, ST_TO_GT_GE_POT}
};

const Int16U SelfTestHV1Board[ST_HV_BOARD_STAGES][ST_HV_BOARD_RELAYS] =
{
		{E_POT_PE_1, GE_PE_1, OL_E_POT_COMM_1, OL_GE_COMM_1, MC_G_C_POT_1, MC_GE_GT_GE_1, MC_G_LSL_G_1, MC_E_POT_LSL_POTN_1, MC_C_POT_LSL_POTN_1, ST_TI_GT_G, ST_TO_LSL_GE, IL_GT_G_COMM, IL_GT_GE_COMM, IL_LSL_G_COMM, IL_LSL_GE_COMM, IL_GT_G_GE, IL_LSL_G_GE},
		{MC_E_POT_GT_GE_POT_1, MC_E_POT_LSL_POTP_1, OL_GE_COMM_1, MC_GE_GT_G_1, MC_G_GE_1, MC_G_GT_G_1, MC_G_GT_GE_1, OL_C_POT_COMM_1, MC_C_POT_LSL_POTP_1, G_PE_1, C_POT_PE_1, ST_TI_GT_G_POT, ST_TO_GT_GE, IL_GT_G_POT_COMM, IL_GT_GE_POT_COMM, IL_GT_G_GE_POT, IL_GT_G_GE_POT},
		{MC_E_POT_GT_GE_POT_1, MC_E_POT_LSL_POTN_1, ST_TI_LSL_POTP, ST_TO_GT_GE_POT, IL_LSL_POTP_COMM, IL_LSL_POTN_COMM, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS},
		{MC_E_POT_GT_GE_POT_1, MC_E_POT_LSL_POTN_1, OL_GE_COMM_1, MC_GE_LSL_GE_1, MC_G_GE_1, OL_G_COMM_1, MC_G_GT_G_POT_1, ST_TI_LSL_G, ST_TO_LSL_POTN, IL_GT_G_POT_COMM, IL_GT_GE_POT_COMM, IL_LSL_G_COMM, IL_LSL_GE_COMM, IL_GT_G_GE_POT, IL_LSL_G_GE, IL_LSL_G_GE, IL_LSL_G_GE}
};

const Int16U SelfTestHV2Board[ST_HV_BOARD_STAGES][ST_HV_BOARD_RELAYS] =
{
		{E_POT_PE_2, GE_PE_2, OL_E_POT_COMM_2, OL_GE_COMM_2, MC_G_C_POT_2, MC_GE_GT_GE_2, MC_G_LSL_G_2, MC_E_POT_LSL_POTN_2, MC_C_POT_LSL_POTN_2, ST_TI_GT_G, ST_TO_LSL_GE, IL_GT_G_COMM, IL_GT_GE_COMM, IL_LSL_G_COMM, IL_LSL_GE_COMM, IL_GT_G_GE, IL_LSL_G_GE},
		{MC_E_POT_GT_GE_POT_2, MC_E_POT_LSL_POTP_2, OL_GE_COMM_2, MC_GE_GT_G_2, MC_G_GE_2, MC_G_GT_G_2, MC_G_GT_GE_2, OL_C_POT_COMM_2, MC_C_POT_LSL_POTP_2, G_PE_2, C_POT_PE_2, ST_TI_GT_G_POT, ST_TO_GT_GE, IL_GT_G_POT_COMM, IL_GT_GE_POT_COMM, IL_GT_G_GE_POT, IL_GT_G_GE_POT},
		{MC_E_POT_GT_GE_POT_2, MC_E_POT_LSL_POTN_2, ST_TI_LSL_POTP, ST_TO_GT_GE_POT, IL_LSL_POTP_COMM, IL_LSL_POTN_COMM, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS, IL_LSL_POTS},
		{MC_E_POT_GT_GE_POT_2, MC_E_POT_LSL_POTN_2, OL_GE_COMM_2, MC_GE_LSL_GE_2, MC_G_GE_2, OL_G_COMM_2, MC_G_GT_G_POT_2, ST_TI_LSL_G, ST_TO_LSL_POTN, IL_GT_G_POT_COMM, IL_GT_GE_POT_COMM, IL_LSL_G_COMM, IL_LSL_GE_COMM, IL_GT_G_GE_POT, IL_LSL_G_GE, IL_LSL_G_GE, IL_LSL_G_GE}
};

